name: Run tests on a PR
on:
  workflow_dispatch:
    inputs:
      prID:
        description: 'The ID of the Pull Request'
        required: true
jobs:
  test-pr:
    runs-on: ubuntu-18.04
    steps:
      -
        name: Get PR Info for Tests
        id: get-pr-info
        run: |
          PRINFO=$(curl -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/benjamin-maynard/kubernetes-cloud-mysql-backup/pulls/${{ github.event.inputs.prID }})
          PRHEAD=$(echo $PRINFO | jq -r .head.repo.full_name)
          PRSHA=$(echo $PRINFO | jq -r .head.sha)
          echo "::set-output name=PRHEAD::$PRHEAD"
          echo "::set-output name=PRSHA::$PRSHA"
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.get-pr-info.outputs.PRHEAD }}
          ref: ${{ steps.get-pr-info.outputs.PRSHA }}