name: Run tests on a PR
on:
  workflow_dispatch:
    inputs:
      prID:
        description: 'The ID of the Pull Request to test'
        required: true
jobs:
  test-pr:
    runs-on: ubuntu-18.04
    steps:
      -
        name: Get PR Info for Tests
        id: get-pr-info
        run: |
          PRINFO=$(curl -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/benjamin-maynard/kubernetes-cloud-mysql-backup/pulls/${{ github.event.inputs.prID }})
          PRHEAD=$(echo $PRINFO | jq -r .head.repo.full_name)
          PRSHA=$(echo $PRINFO | jq -r .head.sha)
          echo "::set-output name=PRHEAD::$PRHEAD"
          echo "::set-output name=PRSHA::$PRSHA"
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.get-pr-info.outputs.PRHEAD }}
          ref: ${{ steps.get-pr-info.outputs.PRSHA }}
      -
        name: Comment on PR
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/benjamin-maynard/test-workflow/issues/1/comments -d '{"body":":white_check_mark: All tests passed successfully. Please see the [Github Actions Run](https://github.com/benjamin-maynard/test-workflow/actions/runs/${{ github.run_id }}) for more details.\n\n**Note:** Tests are performed using the latest [pr-tests.yaml](https://github.com/benjamin-maynard/kubernetes-cloud-mysql-backup/blob/master/.github/workflows/run-pr-tests.yaml) config as defined in the HEAD of the master branch. If this PR includes modified set of tests they have not been executed."}'
      -
        name: Comment on PR Failure
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/benjamin-maynard/test-workflow/issues/1/comments -d '{"body":":x: Tests did not complete successfully. Please see the [Github Actions Run](https://github.com/benjamin-maynard/test-workflow/actions/runs/${{ github.run_id }}) for more details.\n\n**Note:** Tests are performed using the latest [pr-tests.yaml](https://github.com/benjamin-maynard/kubernetes-cloud-mysql-backup/blob/master/.github/workflows/run-pr-tests.yaml) config as defined in the HEAD of the master branch. If this PR includes modified set of tests they have not been executed."}'